# Generated by Django 6.0.3 on 2026-03-19 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'E-mail'), ('phone', 'Telefone'), ('in_person', 'Presencial'), ('system', 'Sistema')], max_length=20, verbose_name='Canal')),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], default='outbound', max_length=20, verbose_name='Direção')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Assunto')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_automated', models.BooleanField(default=False, verbose_name='Automatizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do template')),
                ('template_type', models.CharField(choices=[('reminder', 'Lembrete'), ('welcome', 'Boas-vindas'), ('follow_up', 'Follow-up'), ('confirmation', 'Confirmação'), ('custom', 'Personalizado')], default='custom', max_length=20, verbose_name='Tipo')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Assunto')),
                ('content', models.TextField(help_text='Use {nome}, {empresa}, {data}, {hora} como variáveis.', verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagens',
                'ordering': ['name'],
            },
        ),
    ]
